apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: infra
manifests:
  rawYaml:
    - deploy/postgres/k8s/statefulset.yaml
    - deploy/postgres/k8s/service.yaml
    - deploy/postgres/k8s/secret.yaml
---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: migrate
requires:
  - configs:
      - infra
    path: .
build:
  local:
    push: true
  artifacts:
    - image: order-migrate
      docker:
        dockerfile: deploy/order/images/migrate.Dockerfile
manifests:
  rawYaml:
    - deploy/order/k8s/migrate-job.yaml
---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: services
requires:
  - configs:
      - infra
    path: .
build:
  local:
    push: true
  artifacts:
    - image: gateway
      ko:
        main: ./cmd/gateway
    - image: order
      ko:
        main: ./cmd/order
manifests:
  rawYaml:
    - deploy/gateway/k8s/deployment.yaml
    - deploy/gateway/k8s/service.yaml
    - deploy/order/k8s/deployment.yaml
    - deploy/order/k8s/service.yaml
