---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: infra
deploy:
  kubectl: {}
manifests:
  kustomize:
    paths:
      - deploy/k8s/namespaces
      - deploy/k8s/postgres
---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: observability
requires:
  - configs: [infra]
deploy:
  helm:
    releases:
      - name: tempo
        namespace: observability
        remoteChart: tempo
        repo: https://grafana.github.io/helm-charts
        version: 1.24.1
        valuesFiles:
          - deploy/helm/tempo/dev-values.yaml
      - name: alloy
        namespace: observability
        remoteChart: alloy
        repo: https://grafana.github.io/helm-charts
        version: 1.5.1
        valuesFiles:
          - deploy/helm/alloy/dev-values.yaml
      - name: grafana
        namespace: observability
        remoteChart: grafana
        repo: https://grafana.github.io/helm-charts
        version: 10.4.1
        valuesFiles:
          - deploy/helm/grafana/dev-values.yaml
---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: migrate
requires:
  - configs: [infra]
build:
  local:
    push: true
  artifacts:
    - image: order-migrate
      docker:
        dockerfile: deploy/docker/order/migrate.Dockerfile
deploy:
  kubectl: {}
manifests:
  kustomize:
    paths:
      - deploy/k8s/migrate
---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: services
requires:
  - configs: [migrate, observability]
build:
  local:
    push: true
  artifacts:
    - image: gateway
      ko:
        main: ./cmd/gateway
    - image: order
      ko:
        main: ./cmd/order
deploy:
  kubectl: {}
manifests:
  kustomize:
    paths:
      - deploy/k8s/gateway
      - deploy/k8s/order
