apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: food-delivery-eda
build:
  local:
    push: true
  artifacts:
    - image: gateway
      ko:
        main: ./cmd/gateway
    - image: order
      ko:
        main: ./cmd/order
manifests:
  rawYaml:
    - deploy/k8s/gateway.yaml
    - deploy/k8s/order.yaml
