apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: infra
deploy:
  kubectl: {}
manifests:
  rawYaml:
    - deploy/k8s/namespaces/*.yaml
    - deploy/k8s/postgres/secret.yaml
    - deploy/k8s/postgres/service.yaml
    - deploy/k8s/postgres/statefulset.yaml
---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: migrate
requires:
  - configs: [infra]
build:
  local:
    push: true
  artifacts:
    - image: order-migrate
      docker:
        dockerfile: deploy/images/order/migrate.Dockerfile
deploy:
  kubectl: {}
manifests:
  rawYaml:
    - deploy/k8s/order/migrate-job.yaml
---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: services
requires:
  - configs: [migrate]
build:
  local:
    push: true
  artifacts:
    - image: gateway
      ko:
        main: ./cmd/gateway
    - image: order
      ko:
        main: ./cmd/order
deploy:
  kubectl: {}
manifests:
  rawYaml:
    - deploy/k8s/gateway/deployment.yaml
    - deploy/k8s/gateway/service.yaml
    - deploy/k8s/order/deployment.yaml
    - deploy/k8s/order/service.yaml
